### ISSUE TITLE
Missing option to choose subject

### ISSUE THREAD

**Issue by ShFil119** [hpcsc/upload-bintray-docker-action#3]
For example if you wanna you use organization's repo.

**Comment by hpcsc** [comment]
@ShFil119 hi, do you have an example of what do you want to achieve? if just uploading to an organisation repo, subject is the username, so you can do:

```
uses: hpcsc/upload-bintray-docker-action@v1
with:
  repository: my-bintray-repository
  package: my-bintray-package
  version: 0.1.0
  sourcePath: ./bin/my-binary-*
  username: your-organisation-name
  apiKey: ${{secrets.BINTRAY_API_KEY}}
```
